name: Push Image to GCP

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'debug'
      release_name:
        description: 'Release Name'
        required: false
        default: 'dev'

permissions:
  contents: 'read'
  id-token: 'write'
    
env:
  GCP_IMAGE_NAME: londemo-dev
  REPOSITORY: londemo-docker-images
  PROJECT_ID: skycrate
  REPO_REGION: europe-west2-docker.pkg.dev
  IMAGE_TAG: latest
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RELEASE_NAME: ${{ github.event.inputs.release_name || 'unset'}}      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2
    
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        project_id: 'skycrate'
        workload_identity_provider: projects/714604549924/locations/global/workloadIdentityPools/github/providers/ipsos-bg-ops-pa-repos
        service_account: github-images-srvc@skycrate.iam.gserviceaccount.com
      
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: europe-west2-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    
    - name: Build and Push the Function Image
      uses: docker/build-push-action@v3
      with:
          context: .
          file: ./Dockerfile
          no-cache: true
          push: true
          provenance: false
          tags: ${{ env.REPO_REGION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.GCP_IMAGE_NAME }}:${{ env.IMAGE_TAG }}